services:
  app:
    image: node:18-alpine
    container_name: node_app_bai8
    depends_on:
      - db_node
    command: sleep infinity # Lệnh này giúp container "sống" mãi mãi để bạn chụp hình
  db_node:
    image: mysql:8.0
    container_name: mysql_db_bai8
    environment:
      MYSQL_ROOT_PASSWORD: root
