spring.application.name=Payment-Service
server.port=8084
server.address=0.0.0.0

spring.datasource.url=jdbc:h2:file:~/payment_sba_db;AUTO_SERVER=TRUE;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# --- GIAO TIẾP MICROSERVICES (LAN DEPLOYMENT) ---
order.service.url=${ORDER_SERVICE_URL:http://localhost:8083}

# Redis Configuration (for Pub/Sub)
spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update

