version: "3.8"

services:
  redis:
    image: redis:7-alpine
    container_name: redis_cache_only
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --requirepass Redis123!@#
    restart: unless-stopped
    environment:
      - REDIS_PASSWORD=Redis123!@#

volumes:
  redis_data: