version: "3.8"

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus_bai12
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  # --- Grafana: Giao diện  ---
  grafana:
    image: grafana/grafana:latest
    container_name: grafana_bai12
    ports:
      - "3002:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
