spring.application.name=Order-Service
server.port=8083

spring.datasource.url=jdbc:h2:file:~/order_sba_db;AUTO_SERVER=TRUE;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# --- GIAO TIẾP MICROSERVICES (LAN DEPLOYMENT) ---
# Nếu chạy ở máy khác trong mạng LAN, đổi localhost thành IP máy đó (VD: http://192.168.1.5:8082)
#food.service.url=http://192.168.137.122:8082
#user.service.url=http://192.168.137.235:8081
#payment.service.url=http://192.168.137.213:8084

food.service.url=http://localhost:8082
user.service.url=http://localhost:8081
payment.service.url=http://localhost:8084
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
spring.kafka.bootstrap-servers=localhost:9092

# Redis Cloud Config
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT:19994}
spring.data.redis.password=${REDIS_PASSWORD}