# Đặt mật khẩu cho Redis
requirepass kimkim0110

# Giới hạn bộ nhớ tối đa là 100MB để không làm treo MacBook
maxmemory 100mb
maxmemory-policy allkeys-lru

# Cho phép Redis lưu dữ liệu xuống đĩa sau mỗi 60 giây nếu có ít nhất 1 thay đổi
save 60 1